server:
  port: 8080
  servlet:
    context-path: /nemo

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nemo?characterEncoding=utf-8
    username: root
    password:

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.rumofuture.nemo.model.domain, com.rumofuture.nemo.model.entity
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.rumofuture.nemo.repository: debug
